development:
  adapter: postgresql
  encoding: unicode
  database: thankyouworld_development
  pool: 5
  username: root
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: thankyouworld_test
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: thankyouworld_production
  pool: 5
  username: root
  password:
